paths:
  /api/products/:
    get:
      summary: Obtiene todos los products
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos OK desde la DB
        "404":
          description: Not Found
        "500":
          description: Error interno del servidor